            - name: Setup PHP Action
  # You may pin to the exact commit or the version.
  # uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1
  uses: shivammathur/setup-php@2.36.0
  with:
    # Setup PHP version.
    php-version: # optional
    # Setup PHP version from a file.
    php-version-file: # optional
    # Setup PHP extensions.
    extensions: # optional
    # Set base ini file.
    ini-file: # optional, default is production
    # Add values to php.ini.
    ini-values: # optional
    # Setup code coverage driver.
    coverage: # optional
    # Setup popular tools globally.
    tools: # optional
    # GitHub token to use for authentication.
    github-token: # optional, default is ${{ github.token }}
          
